### ISSUE TITLE
Question: is it can work on webassembly?

### ISSUE THREAD

**Issue by crossle** [gkdr/axc#11]

**Comment by gkdr** [comment]
I don't know what the requirements are, but after a short look on the official website I have the impression that there are none.
However, I think that using [libsignal-protocol-javascript](https://github.com/signalapp/libsignal-protocol-javascript) instead is probably what you want to do.

**Comment by crossle** [comment]
lol, the official javascript code, so bad. 😄

**Comment by gkdr** [comment]
i'm assuming that answer was satisfactory :slightly_smiling_face:
