### ISSUE TITLE
Where i can find high level function of client ?

### ISSUE THREAD

**Issue by loguntsov** [gkdr/axc#12]
I don't see implementation for:
```

int axc_handshake_initiate(axc_address * recipient_addr_p, axc_context * ctx_p, axc_handshake ** handshake_init_pp);

int axc_handshake_accept(axc_buf * msg_data_p, axc_address * sender_addr_p, axc_context * ctx_p, axc_handshake ** handshake_response_pp);

int axc_handshake_acknowledge(axc_buf * msg_data_p, axc_handshake * handshake_p, axc_context * ctx_p);
```

where i can find this implementation ? or some examples of this logic ?

**Comment by gkdr** [comment]
`libsignal` removed the support for synchronous session establishment. It seems I forgot to update the header file when I removed the implementation.

**Comment by loguntsov** [comment]
Could you update your message_client code ? 
There is no much information in internet how i can use libsignal-protocol-c.
Your example can be very helpful.
Thank you.

**Comment by loguntsov** [comment]
I implemented Erlang binding for libsignal-protocol-c.
So you can see what is working and how. You can update your code fastly.
https://github.com/loguntsov/erl_signal/tree/master/c_src


The main trouble what i meet - is i can't find actual example of usage library. 
There is no serialise/deserialise functions for pre_signed_key_bundle. So i just made it myself.
Feel free to ask me something.
Hope i can help you to make super client for this library :)
