### ISSUE TITLE
Bundled libsignal-protocol-c 2.3.2 outdated, upstream at 2.3.3 by now

### ISSUE THREAD

**Issue by hartwork** [gkdr/axc#19]
Hi!

I noticed that the bundled libsignal-protocol-c is at version 2.3.2 while [upstream is at release 2.3.3 by now](https://github.com/signalapp/libsignal-protocol-c/releases). Are there plans to upgrade?

Best, Sebastian

**Comment by gkdr** [comment]
hi, thanks for bringing it to my attention. should not be a problem.

**Comment by Neustradamus** [comment]
@hartwork, @gkdr: This issue can be closed now, I think :)

**Comment by gkdr** [comment]
@Neustradamus this issue would have been closed automatically as soon as the linked commit is on the `master` branch because it uses a github keyword in the commit message

**Comment by hartwork** [comment]
I was already wondering why it wasn't effective — so the target branch made the difference, good to know.

**Comment by Neustradamus** [comment]
Sorry, I have not seen that it was in "dev" branch...
Maybe good to reopen?

**Comment by gkdr** [comment]
don't worry about it, i was just explaining the situation :slightly_smiling_face: it is indeed a bit confusing.
