### ISSUE TITLE
Call "session_builder_free(session_builder_p);" still uses internal libsignal-protocol-c non-API code

### ISSUE THREAD

**Issue by hartwork** [gkdr/axc#20]
This is a follow-up to #16.

I just learned that aee726aa8aaba38d0b99e47b60d4ce1a3815cdd2 is incomplete: There is one more call to non-API function `session_builder_free` at https://github.com/gkdr/axc/blob/27e0544319eea501170299ffaf8c48bb40797504/src/axc.c#L1051 Link errors brought this to my attention while trying to unbundle `libsignal-protocol-c`.
Is there a way to clean-up the session using public API?

Best, Sebastian

**Comment by gkdr** [comment]
thanks for pointing it out. i'll have a look, i'm sure it's doable via the public API.

(cringing at "line 1051"...)

**Comment by gkdr** [comment]
why do you think it's not part of the public API? the docs of `session_builder.h` make it seem like it's not only intended for internal use, and grepping it reveals that it's mentioned in the readme as well.

**Comment by hartwork** [comment]
My bad, I think I jumped to conclusions too quickly here and should have double checked. No more link errors now, I think you're right. Closing as invalid.

**Comment by hartwork** [comment]
PS: If you're interested, here's how I unbundled libsignal-protocol-c in Gentoo now: https://github.com/gentoo/gentoo/commit/73f5dc714de94558c1714e42f6e6233d64e92071

**Comment by gkdr** [comment]
good to know, glad the issue was resolved so quickly.

i am interested, thanks for linking it :slightly_smiling_face:
